name: AirSneakBoots
author: "jasonwynn10"
version: 0.1.3
api:
 - 3.0.0
 - 3.0.0-ALPHA7
main: jasonwynn10\AirBoots\Main
description: "Adds in boots that give the player the ability to sneak on air"
commands:
  boots:
    usage: "/boots"
    description: "Gives the player the special boots"
    permission: boots
permissions:
  boots:
    default: op